name: Conda Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Update to latest version

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda
          cache-downloads: true
          auto-update-conda: false
          activate-environment: test
          python-version: "3.12"

      - name: Setup conda-build and anaconda-client
        run: |
          mamba install -q conda-build anaconda-client conda-verify

      - name: Build package
        run: |
          conda build purge-all
          conda config --set solver libmamba
          conda config --set channel_priority strict
          conda build recipe --suppress-variables --override-channels --channel conda-forge --channel bioconda --no-anaconda-upload --output-folder ./
